name: Deploy website to dev on dev.eduhelp.lv
on:
  push:
    branches:
      - development
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      run: docker build -t edu-help-website .

    - name: Push Docker image
      run: |
        docker tag edu-help-website ${{ secrets.DOCKERHUB_USERNAME }}/edu-help-website:dev
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/edu-help-website:dev

    - name: Run Docker container
      run: |
        docker run --name edu-temp-container -d ${{ secrets.DOCKERHUB_USERNAME }}/edu-help-website:dev tail -f /dev/null
        docker cp edu-temp-container:/usr/share/nginx/html/dist ./edu-built-app
        docker rm -f edu-temp-container

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ftp.eduhelp.lv
          username: ${{ secrets.DEV_FTP_USERNAME }}
          password: ${{ secrets.DEV_FTP_PASSWORD }}
          local-dir: ./edu-built-app/
