name: Build and deploy Eduhelp website on selected env
on:
  workflow_dispatch:

env:
  docker_tag: ${{ github.ref == 'refs/heads/master' && 'latest' || 'dev' }}
  ftp_username: ${{ github.ref == 'refs/heads/master' && secrets.PROD_FTP_USERNAME || secrets.DEV_FTP_USERNAME }}
  ftp_password: ${{ github.ref == 'refs/heads/master' && secrets.PROD_FTP_PASSWORD || secrets.DEV_FTP_PASSWORD }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        if: ${{ github.ref != 'refs/heads/master' && github.ref != 'refs/heads/development' }}
        run: |
          echo 'Wrong branch ${{github.ref}}'
          exit 1

      - name: Get latest code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t edu-help-website .

      - name: Push Docker image
        run: |
          docker tag edu-help-website ${{ secrets.DOCKERHUB_USERNAME }}/edu-help-website:${{ env.docker_tag }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/edu-help-website:${{ env.docker_tag }}

      - name: Run Docker container
        run: |
          docker run --name edu-temp-container -d ${{ secrets.DOCKERHUB_USERNAME }}/edu-help-website:${{ env.docker_tag }} tail -f /dev/null
          docker cp edu-temp-container:/usr/share/nginx/html/dist ./edu-built-app
          docker rm -f edu-temp-container

      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ftp.eduhelp.lv
          username: ${{ env.ftp_username }}
          password: ${{ env.ftp_password }}
          local-dir: ./edu-built-app/
